config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  resources :users do
    member do
      get :bookmarking
    end
  end
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :shops do
    resources :reviews, only: [:create, :destroy]
  end
  resources :bookmarks, only: [:create, :destroy]
  post "/guest_login", to: "sessions#guest_login"
  resources :tags do
    get :shops, to: "shops#tag_search"
  end
  resources :likes, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @animal_tags = Tag.where(tag_type: "animal")
    @env_tags = Tag.where(tag_type: "env")
  end

  def about
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="explanation_wrap center">
  <h2 class="main_title">What is ANIMAL CAFE?</h2>
  <p>animal cafeは動物カフェを共有できるサービスです。</p>
  <p>自分が行ったお店を投稿すれば、動物カフェを他の人と手軽に共有できます。</p>
  <p>また近くの動物カフェをエリア検索して見つけることができます。</p>
  <p>自分が行った動物カフェを動物好きな人と共有したい</p>
  <p>今度の休日、動物に癒されにカフェに行きたい時などに</p>
  <p>animal cafeをぜひご利用ください！</p>
  <h3 class="fas fa-angle-double-down"></h3>
  <div>
    <%= link_to icon("fas", "paw", "新規登録する"), signup_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="top_main">
  <div class="home_search_area">
    <div class="tabs">
      <div class="tab_btns">
        <span class="content1">エリア検索</span>
        <span class="content2">タグから探す</span>
        <div id="lamp" class="content1"></div>
      </div>
      <div class="tab_content">
        <div class="content1">
          <p>動物カフェを探しに行こう!</p>
          <%= form_with(url: shops_path, method: :get, scope: :search, local: true, class: "search_form") do |f| %>
            <%= f.text_field :address, class: "form-control", id: "home_search_address", placeholder: "エリアで検索" %>
            <%= f.submit "検索する", class: "btn btn-danger" %>
          <% end %>
          <%= link_to icon("far", "hand-point-right", "animal cafe とは?"), about_path, class: "explanation_link" %>
        </div>
        <div class="content2">
          <div class="tag_search_area">
            <% @animal_tags.each do |tag| %>
              <% tag_name = "#{tag.name}(#{tag.shops.count})" %>
              <%= link_to tag_name, tag_shops_path(tag) %>
            <% end %>
            <% @env_tags.each do |tag| %>
              <% tag_name = "#{tag.name}(#{tag.shops.count})" %>
              <%= link_to tag_name, tag_shops_path(tag) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<h2 class="app_explanation_word"><i class="fas fa-book-reader"></i>animalcafeの使い方</h2>
<div class="app_explanation_area">
  <div class="card card_skin">
    <div class="card_image card_imgframe"></div>
    <div class="card_textbox">
      <div class="card_title">
        店舗投稿機能
      </div>
      <div class="card_text">
        店舗を投稿することで動物好きな人と、
        動物カフェを共有できます
      </div>
    </div>
  </div>
  <div class="card card_skin">
    <div class="card_image card_imgframe2"></div>
    <div class="card_textbox">
      <div class="card_title">
        ブックマーク機能
      </div>
      <div class="card_text">
        検索して気になった動物カフェをブックマークできます
      </div>
    </div>
  </div>
  <div class="card card_skin">
    <div class="card_image card_imgframe3"></div>
    <div class="card_textbox">
      <div class="card_title">
        クチコミ機能
      </div>
      <div class="card_text">
        実際に行ったことのある店舗にクチコミできます
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag "top/tab_menu" %>