config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  resources :users do
    member do
      get :bookmarking
    end
  end
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :shops do
    resources :reviews, only: [:create, :destroy]
  end
  resources :bookmarks, only: [:create, :destroy]
  post "/guest_login", to: "sessions#guest_login"
  resources :tags do
    get :shops, to: "shops#tag_search"
  end
  resources :likes, only: [:create, :destroy]
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :likes, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  # 検索メソッド
  scope :search, -> (search_params) do
    return if search_params[:address].blank?
    address_like(search_params[:address])
  end

  scope :address_like, -> (address) { where("address LIKE ?", "%#{address}%") }

  # geocode
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :user_id, presence: true
  validates :name, presence: true,
                   length: { maximum: 50 },
                   uniqueness: true
  validates :started_at, presence: true
  validates :closed_at, presence: true
  validates :regular_holiday, presence: true
  validates :address, presence: true,
                      uniqueness: true
  validates :nearest_station, presence: true,
                              length: { maximum: 30 }
  validates :low_budget, presence: true
  validates :description, presence: true,
                          length: { maximum: 300 }

  # active_storage
  has_many_attached :images
  validates :images,
            content_type: {
              in: %w(image/jpeg image/gif image/png),
              message: "のフォーマットが無効です",
            },
            size: {
              less_than: 5.megabytes,
              message: "は5MB未満のファイルを選択してください",
            },
            limit: {
              max: 4,
              message: "は最大4枚までです",
            }

  # 店舗レビューの平均点
  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f
    end
  end

  # 店舗レビューの平均の割合
  def avg_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f / 5 * 100
    end
  end

  # 動物のタグを保存する
  def save_animal_tag(post_tags)
    current_tags = tags.where(tag_type: "animal").pluck(:name) unless tags.nil?
    old_tags = current_tags - post_tags
    new_tags = post_tags - current_tags

    old_tags.each do |old_tag|
      tags.delete(Tag.find_by(name: old_tag))
    end

    new_tags.each do |new_tag|
      post_tag = Tag.find_or_create_by(name: new_tag)
      post_tag.tag_type = "animal"

      tags << post_tag
    end
  end

  # 設備のタグを保存する
  def save_env_tag(post_tags)
    current_tags = tags.where(tag_type: "env").pluck(:name) unless tags.nil?
    old_tags = current_tags - post_tags
    new_tags = post_tags - current_tags

    old_tags.each do |old_tag|
      tags.delete(Tag.find_by(name: old_tag))
    end

    new_tags.each do |new_tag|
      post_tag = Tag.find_or_create_by(name: new_tag)
      post_tag.tag_type = "env"

      tags << post_tag
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_shop_poster, only: [:edit, :update, :destroy]

  def index
    @shops = Shop.search(user_search_params).includes(:reviews, :user).paginate(page: params[:page], per_page: 6).with_attached_images
  end

  def new
    @shop = current_user.shops.build
  end

  def show
    @shop = Shop.find(params[:id])
    @tags = @shop.tags
    @review = Review.new
    @reviews = @shop.reviews.includes(:user)
  end

  def create
    @shop = current_user.shops.build(shop_params)
    animal_tags = params[:shop][:tag_animal].split(" ") if params[:shop][:tag_animal].present?
    env_tags = params[:shop][:tag_env].split(" ") if params[:shop][:tag_env].present?
    if @shop.save
      @shop.save_animal_tag(animal_tags) if animal_tags.present?
      @shop.save_env_tag(env_tags) if env_tags.present?
      flash[:success] = "店舗を投稿しました!"
      redirect_to @shop
    else
      render "new"
    end
  end

  def edit
  end

  def update
    animal_tags = params[:shop][:tag_animal].split(" ") if params[:shop][:tag_animal].present?
    env_tags = params[:shop][:tag_env].split(" ") if params[:shop][:tag_env].present?
    if @shop.update(shop_params)
      @shop.save_animal_tag(animal_tags) if animal_tags.present?
      @shop.save_env_tag(env_tags) if env_tags.present?
      flash[:success] = "店舗情報を更新しました"
      redirect_to @shop
    else
      render "edit"
    end
  end

  def destroy
    @shop.destroy
    flash[:success] = "店舗を削除しました"
    redirect_to @shop.user
  end

  def tag_search
    tag = Tag.find(params[:tag_id])
    @shops = tag.shops.paginate(page: params[:page], per_page: 6)
    render "index" and return
  end

  private

  def shop_params
    params.require(:shop).permit(
      :name,
      :started_at,
      :closed_at,
      :regular_holiday,
      :phone_number,
      :address,
      :low_budget,
      :high_budget,
      :description,
      :nearest_station,
      images: []
    )
  end

  def user_search_params
    params.fetch(:search, {}).permit(:address)
  end

  def correct_shop_poster
    @shop = current_user.shops.find_by(id: params[:id])
    redirect_to root_url if @shop.nil?
  end
end

app/views/shops/_bookmark.html.erb
<%= form_with(model: current_user.bookmarks.build) do |f| %>
  <div><%= hidden_field_tag :shop_id, shop.id %></div>
  <%= f.button type: "submit", class: "bookmark_btn" do %>
    <i class="far fa-bookmark bm"></i>
  <% end %>
<% end %>

app/views/shops/_bookmark_form.html.erb
<% unless current_user?(shop.user) %>
  <div id="bookmark_form">
    <% if current_user.bookmarking?(shop) %>
      <%= render partial: "shops/unbookmark", locals: { shop: shop } %>
    <% else %>
      <%= render partial: "shops/bookmark", locals: { shop: shop } %>
    <% end %>
  </div>
<% end %>

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", placeholder: "ニャンニャン猫カフェ" %>

  <div class="row">
    <div class="col-xs-5">
      <%= f.label :started_at %>
      <%= f.time_field :started_at, class: "form-control" %>
    </div>
    <div class="col-xs-1">
      <div class="wavy_line">〜</div>
    </div>
    <div class="col-xs-5">
      <%= f.label :closed_at %>
      <%= f.time_field :closed_at, class: "form-control" %>
    </div>
  </div>

  <%= f.label :regular_holiday %>
  <%= f.text_field :regular_holiday, class: "form-control", placeholder: "月曜日 / 年中無休 など" %>

  <%= f.label :phone_number %>
  <%= f.telephone_field :phone_number, class: "form-control", placeholder: "123456789" %>

  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control", placeholder: "東京都渋谷区渋谷２丁目２４−１ エクシリア 302号" %>

  <%= f.label :nearest_station %>
  <%= f.text_field :nearest_station, class: "form-control", placeholder: "東京駅" %>

  <div class="row">
    <div class="col-xs-5">
      <%= f.label :low_budget %>
      <%= f.number_field :low_budget, step: "10", class: "form-control", placeholder: 1000 %>
    </div>
    <div class="col-xs-1">
      <div class="wavy_line">〜</div>
    </div>
    <div class="col-xs-5">
      <%= f.label :high_budget %>
      <%= f.number_field :high_budget, step: "10", class: "form-control", placeholder: 2500 %>
    </div>
  </div>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control", placeholder: "かわいい猫ちゃんがいます、人懐っこい子が多いです!お昼になると餌あげタイムもあります！" %>

  <%= f.label :tag_animal %><span>※半角スペースでタグ付けできます</span>
  <%= f.text_field :tag_animal, class: "form-control", placeholder: "猫 マンチカン" %>

  <%= f.label :tag_env %><span>※半角スペースでタグ付けできます</span>
  <%= f.text_field :tag_env, class: "form-control", placeholder: "wifi コンセント 駅近" %>

  <%= f.label :images, "画像(最大4枚)" %>
  <%= f.file_field :images, multiple: true, accept: "image/jpeg, image/gif, image/png" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/shops/_index_shop.html.erb
<% if shops.any? %>
  <div class="container shop_index_frame_wrap">
    <div class="shop_index_frame">
      <p><%= yield(:result_text) %>: <%= shops.count %>件</p>
      <ol class="shops">
        <%= render shops %>
      </ol>
    </div>
  </div>
  <div class="paginate_center">
    <%= will_paginate shops %>
  </div>
<% else %>
  <p><%= yield(:result_text) %>: 0件</p>
<% end %>

app/views/shops/_like.html.erb
<%= form_with(model: current_user.likes.build) do |f| %>
  <div><%= hidden_field_tag :shop_id, shop.id %></div>
  <%= f.button type: "submit", class: "like_btn" do %>
    <i class="far fa-heart like"></i>
    <br><%= shop.likes.count %>
  <% end %>
<% end %>

app/views/shops/_like_form.html.erb
<div id="like_form">
  <% if current_user.like?(shop) %>
    <%= render partial: "shops/unlike", locals: { shop: shop } %>
  <% else %>
    <%= render partial: "shops/like", locals: { shop: shop } %>
  <% end %>
</div>

app/views/shops/_shop.html.erb
<li id="shop-<%= shop.id %>">
  <section class="shop_card">
    <%= link_to shop do %>
      <% if shop.images.attached? %>
        <%= image_tag shop.images.first, class: "card-img" %>
      <% else %>
        <%= image_tag "noimage.png", class: "card-img" %>
      <% end %>
    <% end %>
    <div class="shop_card_content">
      <h1 class="shop_card_title"><%= link_to shop.name, shop %></h1>
      <div class="shop_card_text">
        <div class="avg_score_wrap">
          <div class="avg_score_value"><%= shop.avg_score %></div>
          <div class="avg_score">
            <div class="avg_score_front" style="width: <%= shop.avg_score_percentage %>%">★★★★★</div>
            <div class="avg_score_back">★★★★★</div>
          </div>
          <div class="review_count">クチコミ: <%= shop.reviews.count %>件</div>
        </div>
        <div>
          <i class="fas fa-map-marker-alt"></i><span><%= shop.nearest_station %></span>
          <i class="far fa-clock"></i><span><%= shop.started_at.strftime("%H:%M") %>~<%= shop.closed_at.strftime("%H:%M") %></span>
        </div>
        <div class="timestamp">
          投稿日: <%= time_ago_in_words(shop.created_at) %>前
        </div>
        <% if current_user?(shop.user) %>
          <div class="manipulate_shop">
            <%= link_to icon("far", "edit"), edit_shop_path(shop), class: "edit_icon" %>
            | <%= link_to icon("far", "trash-alt"), shop, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "trash_icon" %>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</li>

app/views/shops/_shop_info_table.html.erb
<table border="1" cellpadding="5">
  <tr>
    <th>店舗名<tdh>
    <td><%= shop.name %></td>
  </tr>
  <tr>
    <th>最寄り駅<tdh>
    <td><%= shop.nearest_station %></td>
  </tr>
  <tr>
    <th>住所<tdh>
    <td>
      <%= shop.address %>
      <div id="map"></div>
    </td>
  </tr>
  <tr>
    <th>電話番号<tdh>
    <td><%= shop.phone_number %></td>
  </tr>
  <tr>
    <th>営業時間<tdh>
    <td><%= shop.started_at.strftime("%H:%M") %>~<%= shop.closed_at.strftime("%H:%M") %></td>
  </tr>
  <tr>
    <th>定休日</th>
    <td><%= shop.regular_holiday %></td>
  </tr>
  <tr>
    <th>平均予算</th>
    <td><%= shop.low_budget %>円~
      <% if shop.high_budget %>
        <%= shop.high_budget %>円
      <% end %>
    </td>
  </tr>
</table>

app/views/shops/_unbookmark.html.erb
<%= form_with(model: current_user.bookmarks.find_by(shop_id: shop.id),
                     html: { method: :delete}) do |f| %>
  <%= f.button type: "submit", class: "bookmark_btn" do %>
    <i class="fas fa-bookmark bm"></i>
  <% end %>
<% end %>

app/views/shops/_unlike.html.erb
<%= form_with(model: current_user.likes.find_by(shop_id: shop.id),
                     html: { method: :delete }) do |f| %>
  <%= f.button type: "submit", class: "like_btn" do %>
    <i class="fas fa-heart like"></i>
    <br><%= shop.likes.count %>
  <% end %>
<% end %>

app/views/shops/edit.html.erb
<% provide(:title, "Edit shop") %>
<% provide(:button_text, "Save changes") %>
<h1>Update shop</h1>
<div class="post_shop_frame">
  <%= render partial: "shops/form", locals: { shop: @shop } %>
</div>

app/views/shops/index.html.erb
<% provide(:title, "Search shops") %>
<% provide(:result_text, "検索結果") %>
<%= render partial: "shops/index_shop", locals: { shops: @shops } %>

app/views/shops/new.html.erb
<% provide(:title, "Post shop") %>
<% provide(:button_text, "Post shop") %>
<h1>Post Shop</h1>
<div class="post_shop_frame">
  <%= render partial: "shops/form", locals: { shop: @shop } %>
</div>

app/views/shops/show.html.erb
<%= provide(:title, @shop.name) %>
<div class="row shop_wrap">
  <div class="col-sm-7">
    <div class="shop_frame">
      <div class="slider">
        <% if @shop.images.attached? %>
          <% @shop.images.each do |image| %>
            <%= image_tag image %>
          <% end %>
        <% else %>
          <%= image_tag "noimage.png" %>
        <% end %>
      </div>
      <div class="like_and_bookmark_wrap">
        <%= render partial: "shops/like_form", locals: { shop: @shop } if logged_in? %>
        <%= render partial: "shops/bookmark_form", locals: { shop: @shop } if logged_in? %>
      </div>
      <div class="shop_name"><%= @shop.name %></div>
      <div class="avg_score_wrap">
        <div class="avg_score_value"><%= @shop.avg_score %></div>
        <div class="avg_score">
          <div class="avg_score_front" style="width: <%= @shop.avg_score_percentage %>%">★★★★★</div>
          <div class="avg_score_back">★★★★★</div>
        </div>
        <div class="review_count">クチコミ: <%= @shop.reviews.count %>件</div>
      </div>
      <i class="fas fa-map-marker-alt"></i><span><%= @shop.nearest_station %></span>
      <i class="far fa-clock"></i><span><%= @shop.started_at.strftime("%H:%M") %>~<%= @shop.closed_at.strftime("%H:%M") %></span>
      <div class="poster_link">投稿者:
        <%= link_to @shop.user do %>
          <% if @shop.user.avater.attached? %>
            <%= image_tag @shop.user.avater.variant(resize_to_fill: [20, 20]), class: "poster_avater_link" %>
          <% else %>
            <%= image_tag "default.png", class: "default_avater_link" %>
          <% end %>
          <%= @shop.user.name %>
        <% end %>
      </div>
      <% if @tags.present? %>
        <div class="shop_tags_area">
          <i class="fas fa-tags"></i>
          <% @tags.each do |tag| %>
            <%= link_to tag.name, tag_shops_path(tag) %>
          <% end %>
        </div>
      <% end %>
      <p>このカフェについて</p>
      <div class="description"><%= @shop.description %></div>
      <%= render partial: "shops/shop_info_table", locals: { shop: @shop } %>
    </div>
  </div>
  <div class="col-sm-5 review_area">
    <p class="review_area_comment">クチコミを投稿する</p>
    <%= render partial: "reviews/form", locals: { review: @review, shop: @shop } %>
    <div class="reviews_frame">
      <% if @reviews.any? %>
        <div class="reviews">
          <%= render partial: "reviews/index", locals: { reviews: @reviews } %>
        </div>
      <% else %>
        <div>クチコミ: 0件</div>
      <% end %>
    </div>
  </div>
</div>

<%= javascript_pack_tag "slick/slide" %>
<script>
  function initMap() {
    const uluru = { lat: <%= @shop.latitude %>, lng: <%= @shop.longitude %> };
    const map = new google.maps.Map(document.getElementById("map"), {
      zoom: 16,
      center: uluru,
    });
    const marker = new google.maps.Marker({
      position: uluru,
      map,
    });
    const contentString =
      "<div><%= @shop.name %></div>" +
      "<div><%= @shop.address %></div>";
    const infowindow = new google.maps.InfoWindow({
      content: contentString,
    });

    marker.addListener("click", () => {
      infowindow.open({
        anchor: marker,
        map,
      });
    });
  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= Rails.application.credentials.dig(:map, :google_map_api_key) %>&callback=initMap"></script>