config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  resources :users do
    member do
      get :bookmarking
    end
  end
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :shops do
    resources :reviews, only: [:create, :destroy]
  end
  resources :bookmarks, only: [:create, :destroy]
  post "/guest_login", to: "sessions#guest_login"
  resources :tags do
    get :shops, to: "shops#tag_search"
  end
  resources :likes, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shops, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarking, through: :bookmarks, source: :shop
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :shop_likes, through: :likes, source: :shop

  attr_accessor :remember_token, :activation_token, :reset_token

  # コールバック
  before_validation :downcase_email
  before_create :create_activation_digest

  # active_storage
  has_one_attached :avater
  validates :avater,
            content_type: {
              in: %w(image/jpeg image/gif image/png),
              message: "のフォーマットが無効です",
            },
            size: {
              less_than: 5.megabytes,
              message: "は5MB未満のファイルを選択してください",
            }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  # has_secure_password
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す has_secure_passwordで使用
  def User.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # テストユーザー作成または検索用のメソッド
  def User.guest
    find_or_create_by!(email: "guest_user@example.com") do |user|
      user.name = "Guest User"
      user.password = SecureRandom.urlsafe_base64
      user.activated = true
      user.activated_at = Time.zone.now
    end
  end

  # 永続セッションのために、ユーザーのdbにハッシュ化した記憶トークンをいれる
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す、rememberとactivationで使用
  def authenticated?(attribute, token) # has_serure_passwordのauthenticateメソッドとほぼ同じ
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # 店舗の投稿をブックマークする
  def bookmark(shop)
    bookmarking << shop
  end

  # ブックマークを解除する
  def unbookmark(shop)
    bookmarks.find_by(shop_id: shop.id).destroy
  end

  # 現在のユーザーがブックマークしてたらtrueを返す
  def bookmarking?(shop)
    bookmarking.include?(shop)
  end

  # 店舗をいいねする
  def like(shop)
    shop_likes << shop
  end

  # 店舗のいいねを解除する
  def unlike(shop)
    likes.find_by(shop_id: shop.id).destroy
  end

  # ユーザーのいいねに店舗が入っていたらtrueを返す
  def like?(shop)
    shop_likes.include?(shop)
  end

  private

  # メールアドレスを全て小文字にしてdbに保存する
  def downcase_email
    email.downcase!
  end

  # メール認証の有効化トークンとダイジェストを作成及び代入する
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :bookmarking]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  before_action :ensure_normal_user, only: :update

  def index
    @users = User.where(activated: true).paginate(page: params[:page], per_page: 20)
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
    @shops = @user.shops.paginate(page: params[:page], per_page: 6)
  end

  def create
    @user = User.new(user_params)
    @user.avater.attach(params[:user][:avater])
    if @user.save
      @user.send_activation_email
      flash[:info] = "アカウント有効化メールを送信しました"
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_url
  end

  def bookmarking
    @user = User.find(params[:id])
    @shops = @user.bookmarking.paginate(page: params[:page], per_page: 6)
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :avater
    )
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def ensure_normal_user
    @user ||= User.find(params[:id])
    if @user.email == "guest_user@example.com"
      flash[:warning] = "ゲストユーザーはプロフィールを編集できません"
      redirect_to root_url
    end
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
    
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
    
  <%= f.label :avater %>
  <%= f.file_field :avater, accept: "image/jpeg, image/gif, image/png" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <% if user.avater.attached? %>
    <%= image_tag user.avater.variant(resize_to_fill: [50, 50]), class: "user_avater" %>
  <% else %>
    <%= image_tag "default.png", class: "default_avater" %>
  <% end %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, data: { confirm: "本当に削除しますか？" } %>
  <% end %>
</li>

app/views/users/_user_menu.html.erb
<div class="row user_frame">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <% if user.avater.attached? %>
          <%= image_tag user.avater.variant(resize_to_fill: [100, 100]), class: "user_avater" %>
        <% else %>
          <%= image_tag "default.png", class: "default_avater" %>
        <% end %>
        <%= user.name %>
      </h1>
    </section>
  </aside>
</div>
<div class="scroll-nav-wrap">
  <div class="scroll-nav">
    <ul>
      <% if current_user?(user) %>
        <li class="scroll-nav-list"><%= link_to icon("far", "edit", "プロフィール編集"), edit_user_path(user) %></li>
      <% end %>
      <li class="scroll-nav-list"><%= link_to icon("fas", "list", "過去の投稿"), user %></li>
      <li class="scroll-nav-list"><%= link_to icon("fas", "bookmark", "ブックマーク"), bookmarking_user_path(user) %></li>
    </ul>
  </div>
</div>

app/views/users/bookmarking.html.erb
<% provide(:title, "Bookmark shops") %>
<%= render partial: "users/user_menu", locals: { user: @user } %>
<% provide(:result_text, "ブックマーク") %>
<%= render partial: "shops/index_shop", locals: { shops: @shops } %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, "Save changes") %>
<h1>Update your profile</h1>
<div class="profile_edit_frame">
  <%= render partial: "users/form", locals: { user: @user } %>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1>All users</h1>

<div class="paginate_center">
  <%= will_paginate %>
</div>

<ul class="users">
  <%= render @users %>
</ul>

<div class="paginate_center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<% provide(:button_text, "Create my account") %>
<h1>Sign up</h1>
<div class="signup_frame">
  <%= render partial: "users/form", locals: { user: @user } %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%= render partial: "users/user_menu", locals: { user: @user } %>
<% provide(:result_text, "過去の投稿") %>
<%= render partial: "shops/index_shop", locals: { shops: @shops } %>