config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  resources :users do
    member do
      get :bookmarking
    end
  end
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :shops do
    resources :reviews, only: [:create, :destroy]
  end
  resources :bookmarks, only: [:create, :destroy]
  post "/guest_login", to: "sessions#guest_login"
  resources :tags do
    get :shops, to: "shops#tag_search"
  end
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>©︎ 2021 ANIMALCAFE.INC. </p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top l-header">
  <div class="container">
    <%= link_to icon("fas", "dog", "ANIMAL CAFE"), root_path, id: "logo" %>
    <%= form_with(url: shops_path, method: :get, scope: :search, local: true, class: "nav navbar-nav navbar-left search_form") do |f| %>
      <%= f.text_field :address, class: "form-control", placeholder: "エリアで検索" %>
      <%= f.submit "検索", class: "btn" %>
    <% end %>
    <nav class="header-nav">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to icon("fas", "user"), current_user, class: "user_icon header_icon" %></li>
          <li><%= link_to icon("fas", "store-alt", "投稿"), new_shop_path, class: "post_shop_icon header_icon" %></li>
          <li><%= link_to icon("fas", "door-open", "ログアウト"), logout_path, method: :delete, class: "logout_icon header_icon" %></li>
        <% else %>
          <li><%= link_to icon("fas", "user-plus", "新規登録"), signup_path, class: "signup_icon header_icon" %></li>
          <li><%= link_to icon("fas", "sign-in-alt", "ログイン"), login_path, class: "login_icon header_icon" %></li>
        <% end %>
      </ul>
    </nav>
    <div class="l-drawer">
      <input class="l-drawer_checkbox" id="drawerCheckbox" type="checkbox">
      <label class="l-drawer_icon" for="drawerCheckbox">
        <span class="l-drawer_icon-parts"></span>
      </label>
      <label class="l-drawer_overlay" for="drawerCheckbox"></label>
      <nav class="l-drawer_menu">
        <ul>
          <% if logged_in? %>
            <li><%= link_to icon("fas", "store-alt", "投稿"), new_shop_path %>
            <li><%= link_to icon("fas", "user", "プロフィール"), current_user %></li>
            <li><%= link_to icon("fas", "door-open", "ログアウト"), logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to icon("fas", "user-plus", "新規登録"), signup_path %></li>
            <li><%= link_to icon("fas", "sign-in-alt", "ログイン"), login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>